# Generated by Django 6.0.1 on 2026-01-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('rasm', models.ImageField(upload_to='images/')),
                ('nomi1', models.CharField(max_length=100)),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
            ],
        ),
    ]
