# Generated by Django 6.0.1 on 2026-01-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_home1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('rasm', models.ImageField(upload_to='images/')),
                ('narx', models.IntegerField()),
                ('nomi1', models.CharField(max_length=200)),
                ('text1', models.TextField()),
                ('rasm1', models.ImageField(upload_to='images/')),
                ('narx1', models.IntegerField()),
                ('nomi2', models.CharField(max_length=200)),
                ('text2', models.TextField()),
                ('rasm2', models.ImageField(upload_to='images/')),
                ('narx2', models.IntegerField()),
            ],
        ),
    ]
