# Generated by Django 6.0.1 on 2026-01-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_home2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('nomi3', models.CharField(max_length=100)),
                ('nomi1', models.CharField(max_length=100)),
                ('text1', models.TextField()),
                ('nomi2', models.CharField(max_length=100)),
                ('text2', models.TextField()),
            ],
        ),
    ]
