# Generated by Django 6.0.1 on 2026-01-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_home3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('madel', models.TextField()),
                ('rasm', models.ImageField(upload_to='images/')),
                ('nomi1', models.CharField(max_length=100)),
                ('madel1', models.TextField()),
                ('rasm1', models.ImageField(upload_to='images/')),
                ('nomi2', models.CharField(max_length=100)),
                ('madel2', models.TextField()),
                ('rasm2', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
