# Generated by Django 6.0.1 on 2026-01-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_home4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('nomi1', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
