# Generated by Django 6.0.1 on 2026-01-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_home5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='images/')),
                ('nomi', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('rasm1', models.ImageField(upload_to='images/')),
                ('nomi1', models.CharField(max_length=200)),
                ('text1', models.TextField()),
                ('rasm2', models.ImageField(upload_to='images/')),
                ('nomi2', models.CharField(max_length=200)),
                ('text2', models.TextField()),
                ('rasm3', models.ImageField(upload_to='images/')),
                ('nomi3', models.CharField(max_length=200)),
                ('text3', models.TextField()),
            ],
        ),
    ]
