# Generated by Django 6.0.1 on 2026-01-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_home6'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('nummer', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
    ]
