# Generated by Django 6.0.1 on 2026-02-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='home5',
            name='rasm',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home5',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
