# Generated by Django 6.0.1 on 2026-03-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_home5_rasm_home5_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home5',
            name='rasm',
        ),
    ]
