# Generated by Django 6.0.1 on 2026-03-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
